language: java
before_install:
- chmod +x gradlew

after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: heroku
  api_key:
    secure: BM/Ai3S6EZN81NaQq3pfOOkKlmWiy78RLIIMuywxBQc7Svqg6IGPfYChBixjn5tgiHUnp1iWZ0ejRCZn5UxLGr7QwZ1f/MGkNOAFJLeol1+g4cX8/8myLWyN1Zyl2YGX1hiH6BecO3fXjwXQGdj0ZfOmp8ABuiHv+cfGUeVQU83dN88Xkh4z5ohUiP3RX0n2OTcwJGMVDt8U9zMhOT0jdDkiluUShWhkEBUoOvvVwOBwTVvsiMcIz8E7n87wIOvJckgKvau+esU9zO37Gw4vCAr5fH2RnkTOGPgUYchzF/e9zhDTiA4nmDLOJEWl4scFeO5WQhklMVpcdVxtofDyKCw0nU026gtA0+fOH5Pt6UIf+pQSa9FfyK9JdZJKhXjih3gySqApAEn4rmoLPE7otMYEuiBZnR7CclfT+HUZiEe7dO4IfVtGvRv9zrdYEngKJ2FpERkNaBSYfFfgjT/TEDUZXIA/RGVfuvURXG0GqZtxj3WGzKV2Rnm4dW6BvcbLUzFzDil/0HAhz7/qnv0C90A2q7iPKq3aRjpchRExz2v3huEuz1axREgleKqpid9oHVxaLyheElPtmO5YkRVoAwTI2gJZ1CRseYX9sKzXHYqR5NR/GF8zhRyF9AWD8y+yHaRLQYLV+pQ+7gErFm5RppS51e/5+wZxCL12iidWOlk=
  app: hverfisbarinn
